"""add shop settings table

Revision ID: 469702d2c5b3
Revises: 5697010639d8
Create Date: 2026-09-12 10:55:46.610120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '469702d2c5b3'
down_revision = '5697010639d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name='shop_settings_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop_settings')
    # ### end Alembic commands ###
