"""add sales and receiving workflow

Revision ID: 5697010639d8
Revises: 8842e5349a61
Create Date: 2026-09-09 22:01:04.738008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5697010639d8'
down_revision = '8842e5349a61'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
