"""add product variants for colour and size

Revision ID: 967cf441f847
Revises: 469702d2c5b3
Create Date: 2026-09-13 23:04:36.252395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '967cf441f847'
down_revision = '469702d2c5b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('colour', sa.String(length=50), nullable=False),
    sa.Column('size', sa.String(length=10), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('stock_quantity >= 0', name='ck_variants_stock_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'colour', 'size', name='uq_variant_product_colour_size')
    )
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.drop_column('products', 'stock_quantity')
    op.add_column('sales', sa.Column('product_variant_id', sa.UUID(), nullable=False))
    op.drop_index('ix_sales_product_id', table_name='sales')
    op.create_index(op.f('ix_sales_product_variant_id'), 'sales', ['product_variant_id'], unique=False)
    op.drop_constraint('sales_product_id_fkey', 'sales', type_='foreignkey')
    op.create_foreign_key(None, 'sales', 'product_variants', ['product_variant_id'], ['id'])
    op.drop_column('sales', 'product_id')
    op.add_column('stock_receiving_items', sa.Column('product_variant_id', sa.UUID(), nullable=True))
    op.add_column('stock_receiving_items', sa.Column('colour', sa.String(length=50), nullable=False))
    op.add_column('stock_receiving_items', sa.Column('size', sa.String(length=10), nullable=False))
    op.create_foreign_key(None, 'stock_receiving_items', 'product_variants', ['product_variant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_receiving_items', type_='foreignkey')
    op.drop_column('stock_receiving_items', 'size')
    op.drop_column('stock_receiving_items', 'colour')
    op.drop_column('stock_receiving_items', 'product_variant_id')
    op.add_column('sales', sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.create_foreign_key('sales_product_id_fkey', 'sales', 'products', ['product_id'], ['id'])
    op.drop_index(op.f('ix_sales_product_variant_id'), table_name='sales')
    op.create_index('ix_sales_product_id', 'sales', ['product_id'], unique=False)
    op.drop_column('sales', 'product_variant_id')
    op.add_column('products', sa.Column('stock_quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_table('product_variants')
    # ### end Alembic commands ###
